name: Build Drivers

on:
  workflow_call:
    # inputs:
    #   platform:
    #     required: true
    #     type: string

jobs:
  build:
    runs-on: windows-2022

    env:
      PLATFORM_X64: "x64"
      PLATFORM_ARM64: "arm64"
      CONFIG: "RELEASE"
      WDS_PATH: "${{ github.workspace }}\\windows-driver-samples"
      OUTPUT_PATH: "${{ github.workspace }}\\extracted_drivers"

    steps:
      - name: Cleanup Workspace
        shell: pwsh
        run: |
          Write-Host "Cleaning workspace: $Env:GITHUB_WORKSPACE"
          Remove-Item -Path (Join-Path $Env:GITHUB_WORKSPACE '*') -Recurse -Force

      - name: Checkout NS
        uses: actions/checkout@v4

      # - name: Checkout Microsoft Driver Samples
      #   uses: actions/checkout@v4
      #   with:
      #     repository: microsoft/Windows-driver-samples
      #     path: ${{ env.WDS_PATH }}
      #     submodules: recursive

      # - name: Delete Other Drivers (For Now...)
      #   shell: pwsh
      #   run: |
      #     Write-Host "[+] Delete other drivers, except multimedia drivers"
      #     cd "$env:WDS_PATH"
      #     Remove-Item "avstream" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "bluetooth" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "filesys" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "general" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "gnss" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "gpio" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "hid" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "input" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "network" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "nfc" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "nfp" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "pofx" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "pos" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "powerlimit" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "print" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "prm" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "sd" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "security" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "sensors" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "serial" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "setup" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "simbatt" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "smartcrd" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "spb" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "storage" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "thermal" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "tools" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "TrEE" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "usb" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "video" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "wia" -Recurse -Force -ErrorAction SilentlyContinue
      #     Remove-Item "wmi" -Recurse -Force -ErrorAction SilentlyContinue

      - name: Load Driver Data JSON
        shell: pwsh
        run: |
          $Platform = "${{ env.PLATFORM_X64 }}"
          $Config   = "${{ env.CONFIG }}"

          $jsonPath = Join-Path $Env:GITHUB_WORKSPACE "driver-data.json"
          Write-Host "Reading JSON from: $jsonPath"
          Write-Host ">>$Platform, $Config"

          $json = Get-Content $jsonPath -Raw
          #$json = $ExecutionContext.InvokeCommand.ExpandString($json)
          $driverData = $json | ConvertFrom-Json
          $driverJson = $driverData | ConvertTo-Json -Depth 10

          Add-Content $Env:GITHUB_ENV "DRIVER_DATA<<EOF"
          Add-Content $Env:GITHUB_ENV $driverJson
          Add-Content $Env:GITHUB_ENV "EOF"


      # - name: Install Nuget Packages
      #   run: |
      #     cd "$env:WDS_PATH"
      #     nuget restore .\packages.config -PackagesDirectory .\packages\

      # - name: Build Drivers
      #   shell: pwsh
      #   run: |
      #     cd "$env:WDS_PATH"
      #     ./Build-Samples.ps1 -Verbose
      #   env:
      #     WDS_Configuration: ${{ Env.CONFIG }}
      #     WDS_Platform: ${{ Env.PLATFORM }}

      # - name: Extract Driver Binaries
      #   shell: pwsh
      #   run: |
      #     $json = $Env:DRIVER_DATA
      #     $driverData = $json | ConvertFrom-Json

      #     Write-Host "--- Starting Extraction for ${{ Env.PLATFORM }}-${{ Env.CONFIG }} ---"
      #     foreach ($driver in $driverData) {
      #       $category    = $($driver.DriverCategory)
      #       $driverName  = $($driver.Driver)
      #       $relativeSrc = $($driver.Path)
      #       $fullSrcPath = Join-Path $env:WDS_PATH $relativeSrc
      #       #$destFolder = Join-Path $env:OUTPUT_PATH "${{ Env.PLATFORM }}-${{ Env.CONFIG }}\$category\$driverName"
      #       $destFolder = Join-Path $env:OUTPUT_PATH "$category\$driverName"
      #       Write-Host "Processing $driverName..."
      #       Write-Host "Copy from $fullSrcPath =>>> $destFolder"

      #       if (Test-Path $fullSrcPath) {
      #           if (!(Test-Path $destFolder)) { New-Item -ItemType Directory -Path $destFolder -Force | Out-Null }
      #           Write-Host "  SUCCESS: Copying from $fullSrcPath"
      #           Copy-Item -Path "$fullSrcPath.cer" -Destination "$fullSrcPath" -Force -Recurse -ErrorAction SilentlyContinue
      #           Copy-Item -Path "$fullSrcPath\*" -Destination $destFolder -Force -Recurse -ErrorAction SilentlyContinue
      #       } else {
      #           Write-Host "  X ERROR: Source not found: $fullSrcPath"
      #       }
      #     }
      #     cd $Env:OUTPUT_PATH
      #     tree /f /a

      # - name: Upload Driver Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ Env.PLATFORM }}
      #     path: ${{ Env.OUTPUT_PATH }}
      #     if-no-files-found: warn

      - name: Print Driver Data JSON
        shell: pwsh
        run: |
          $json = $Env:DRIVER_DATA
          $driverData = $json | ConvertFrom-Json

          $driverData | ForEach-Object { $_ }
          throw "force failing...."
