name: Build Drivers

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      config:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Build Step 1
        shell: pwsh
        run: |
          Write-Host "[+] Build Step 1...."

      - name: Echo input values
        run: |
          echo "Arch: ${{ inputs.arch }}"
          echo "Config: ${{ inputs.config }}"
