name: Build WDS

on:
  workflow_dispatch:

jobs:
  build:
    name: Build driver samples
    runs-on: windows-2022

    env:
      WDS_PATH: "${{ github.workspace }}\\windows-driver-samples"
      CODEQL_BIN: "${{ github.workspace }}\\codeql\codeql.exe"
      X64_DB_PATH: "${{ github.workspace }}\\wds-release-x64"
      ARM64_DB_PATH: "${{ github.workspace }}\\wds-release-x64"
      DEST: "${{ github.workspace }}\\extracted_drivers"

    steps:
      - name: Checkout Microsoft Driver Samples
        uses: actions/checkout@v4
        with:
          repository: microsoft/Windows-driver-samples
          path: ${{ env.WDS_PATH }}
          submodules: recursive

      - name: Download and Extract CodeQL CLI
        shell: pwsh
        run: |
          $CodeqlZip = "codeql-win64.zip"
          $DownloadUrl = "https://github.com/github/codeql-cli-binaries/releases/download/v2.15.4/codeql-win64.zip"

          Write-Host "[+] Downloading CodeQL CLI v2.15.4..."
          curl.exe -L -o $CodeqlZip $DownloadUrl

          Write-Host "[+] Extracting CodeQL..."
          # tar is built-in to Windows Server 2022
          tar.exe -xf $CodeqlZip

          Write-Host "[+] Cleaning up zip..."
          Remove-Item $CodeqlZip

          Write-Host "[+] Verifying CodeQL installation..."
          & $env:CODEQL_BIN --version

      - name: Initialize CodeQL Packs
        shell: pwsh
        run: |
          Write-Host "[+] Download Pack microsoft/windows-drivers@1.0.13..."
          & $env:CODEQL_BIN pack download microsoft/windows-drivers@1.0.13

          Write-Host "[+] Download Pack codeql/cpp-queries@0.9.0..."
          & $env:CODEQL_BIN pack download codeql/cpp-queries@0.9.0

      - name: Creating CodeQL Database & Build Drivers
        shell: pwsh
        run: |
          Write-Host "[+] Creating CodeQL Database..."

          # Use & (call operator) with $env: variables
          & $env:CODEQL_BIN database create "$env:X64_DB_PATH" `
              --language=cpp `
              --command "pwsh -NoProfile -ExecutionPolicy Bypass -File `"$env:WDS_PATH\Build-AllSamples.ps1`" -Configuration Release -Platform x64 -Verbose"

          if ($LASTEXITCODE -ne 0) {
              Write-Error "[!] Database creation failed with error $LASTEXITCODE"
              exit $LASTEXITCODE
          }

      - name: Setup Pre-Requisites
        run: echo Hello, world!

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
