name: Build WDS

on:
  workflow_dispatch:

jobs:
  Build Drivers:
    runs-on: windows-2022

    env:
      WDS_PATH: "${{ github.workspace }}\\windows-driver-samples"
      CODEQL_ZIP: "codeql-win64.zip"
      DEST: "${{ github.workspace }}\\extracted_drivers"

    steps:
      - name: Checkout Microsoft Driver Samples
        uses: actions/checkout@v4
        with:
          repository: microsoft/Windows-driver-samples
          path: ${{ env.WDS_PATH }}
          submodules: recursive

      - name: Download and Extract CodeQL CLI
        shell: pwsh
        run: |
          $CodeqlZip = "codeql-win64.zip"
          $DownloadUrl = "https://github.com/github/codeql-cli-binaries/releases/download/v2.15.4/codeql-win64.zip"

          Write-Host "[+] Downloading CodeQL CLI v2.15.4..."
          curl.exe -L -o $CodeqlZip $DownloadUrl

          Write-Host "[+] Extracting CodeQL..."
          # tar is built-in to Windows Server 2022
          tar.exe -xf $CodeqlZip

          Write-Host "[+] Cleaning up zip..."
          Remove-Item $CodeqlZip

          Write-Host "[+] Verifying CodeQL installation..."
          ./codeql/codeql.exe --version

      - name: Initialize CodeQL Packs
        shell: pwsh
        run: |
          ./codeql/codeql.exe pack download microsoft/windows-drivers@1.0.13
          ./codeql/codeql.exe pack download codeql/cpp-queries@0.9.0

      - name: Setup Pre-Requisites
        run: echo Hello, world!

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
