name: HLK Testing

on:
  workflow_call:
    inputs:
      driverType:
        required: true
        type: string

jobs:
  download-artifacts:
    runs-on: self-hosted

    steps:
      # - name: Cleanup Workspace
      #   shell: powershell
      #   run: |
      #     Write-Host "Cleaning workspace: $Env:GITHUB_WORKSPACE"
      #     Remove-Item -Path (Join-Path $Env:GITHUB_WORKSPACE '*') -Recurse -Force

      # - name: Download all driver build artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     path: build-artifacts

      - name: Verify downloaded artifacts
        shell: powershell
        run: |
          Write-Host "Downloaded artifacts:"
          Get-ChildItem -Recurse build-artifacts

  hlk-run:
    needs: download-artifacts
    runs-on: self-hosted

    strategy:
      max-parallel: 5
      matrix:
        platform:
          - { Name: "Win11_25H2_x64"}

  #   #       - { Name: "Windows10_x86"     }
  #   #       - { Name: "Windows10_x64"     }
  #   #       - { Name: "Win11_22H2_x64"    }
  #   #       - { Name: "Win11_23H2_x64"    }
  #   #       - { Name: "Win11_24H2_x64"    }
  #   #       - { Name: "Win11_25H2_x64"    }
  #   #       - { Name: "Win11_26H1_x64"    }
  #   #       - { Name: "Win11_24H2_arm64"  }
  #   #       - { Name: "Win11_25H2_arm64"  }
  #   #       - { Name: "Win11_26H2_arm64"  }

    steps:
      - name: Verify artifacts are available
        shell: powershell
        run: |
          Write-Host "Artifacts available for HLK:"
          Get-ChildItem -Recurse build-artifacts

      - name: Get machine info
        shell: powershell
        run: |
          $platform = ${{ matrix.platform }}
          $servers = Get-Content "servers.json" -Raw | ConvertFrom-Json

          $server = $servers | Where-Object { $_.platform -eq $platform }

          if (-not $server) {
              throw "No server configuration found for platform: $platform"
          }

          # Controller info
          $controllerIp   = $server.controller.ip
          $controllerUser = $server.controller.username
          $controllerPass = $server.controller.password

          # DUT info
          $dutIp   = $server.dut.ip
          $dutUser = $server.dut.username
          $dutPass = $server.dut.password

          Write-Host "Platform: $platform"
          Write-Host "Controller IP: $controllerIp"
          Write-Host "DUT IP: $dutIp"
