name: Windows Driver Sample HLK Test (Build + HLK)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        arch: [ "x64", "ARM64" ]
        config: [ "Release" ]

    steps:
      - name: Build Driver
        uses: ./.github/workflows/build_ci.yml
        with:
          arch: ${{ matrix.arch }}
          config: ${{ matrix.config }}

  # trigger_build:
  #   uses: ./.github/workflows/build_ci.yml

  # trigger_hlk:
  #   needs: trigger_build
  #   uses: ./.github/workflows/hlk_ci.yml
