
name: Windows Driver Sample HLK Test (Build + HLK)

on:
  workflow_dispatch:

jobs:

  build-samples:
    uses: markand-jk/wds-ns/.github/workflows/build_ci.yml@main
    strategy:
      max-parallel: 1
      matrix:
        arch: [ "x64", "ARM64" ]
        config: [ "Release" ]
    with:
      arch: ${{ matrix.arch }}
      config: ${{ matrix.config }}
    secrets: inherit


  hlk-test:
    needs: build-samples
    uses: markand-jk/wds-ns/.github/workflows/hlk_ci.yml@main
    strategy:
      max-parallel: 5
      matrix:
        category: [ "Debug", "Multimedia" ]
    with:
      category: ${{ matrix.category }}
    secrets: inherit
