name: Windows Driver Sample HLK Test (Build + HLK)

on:
  workflow_dispatch:

jobs:
  build-samples:
    runs-on: windows-2022

    strategy:
      matrix:
        arch: [ "x64", "ARM64" ]
        config: [ "Release" ]

    steps:
      - name: Build Driver
        uses: ${{ github.repository }}/.github/workflows/build_ci.yml@main
        with:
          arch: ${{ matrix.arch }}
          config: ${{ matrix.config }}

  hlk-test:
    needs: [build-samples]
    runs-on: self-hosted

    strategy:
      matrix:
        category:
          - Debug
          - Multimedia

    steps:
      - name: HLK Testing
        uses: ${{ github.repository }}/.github/workflows/hlk_ci.yml@main
        with:
          category: ${{ matrix.category }}


  # trigger_build:
  #   uses: ./.github/workflows/build_ci.yml

  # trigger_hlk:
  #   needs: trigger_build
  #   uses: ./.github/workflows/hlk_ci.yml


          # - Debug
          # # - Filesystem
          # # - GPIO
          # # - IO
          # - Multimedia
          # # - Network
          # # - PCI
          # # - Platform
          # # - Power
          # # - Security
          # # - Sensors
          # # - Storage
          # # - Tool
          # # - USB
          # # - Wireless
